apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pv-time
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pv-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
