apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv-time
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '30'
    volumeHandle: existing-longhorn-volume-pv-time
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv-config
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '30'
    volumeHandle: existing-longhorn-volume-pv-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-time
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
  volumeName: homeassistant-pv-time
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-config
  namespace: home-assistant
  labels:
    app: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
  volumeName: homeassistant-pv-config