apiVersion: v1
kind: Service
metadata:
  name: pihole-lb
  namespace: pihole
  labels:
    app: pihole
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 53
      protocol: UDP
      name: dns
  selector:
    app: pihole
  type: LoadBalancer