apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: givtcp-pv-config
  namespace: home-assistant
  labels:
    app: givtcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
