# This is to redeploy givtcp with the existing dataset on th PV still in place.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: givtcp
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: givtcp
  template:
    metadata:
      labels:
        app: givtcp
    spec:
      containers:
      - name: givtcp
        image: "britkat/giv_tcp-ma:latest" # Or a specific version
        volumeMounts:
        - name: givtcp-pv-config
          mountPath: /config/GivTCP
      volumes:
        - name: givtcp-config
          configMap:
            name: givtcp-config
        - name: givtcp-pv-config
          persistentVolumeClaim:
            claimName: givtcp-pv-config