apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-frontend
  namespace: home-assistant
  labels:
    app: zigbee2mqtt
spec:
  ports:
    - port: 8080
  selector:
    app: zigbee2mqtt
  type: LoadBalancer