apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "600Mi"
          requests:
            memory: "600Mi"
        volumeMounts:
          - name: zigbee2mqtt-persistent-storage
            mountPath: /app/data
        env:
        - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
          value: "admin"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
          value: "admin@123"
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: "mqtt://mosquitto.home-assistant.svc.cluster.local"
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
          value: "true"
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
          value: "8080"
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
          value: "true"
      restartPolicy: Always
      volumes:
        - name: zigbee2mqtt-persistent-storage
          persistentVolumeClaim:
            claimName: zigbee2mqtt-pv-claim