apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: home-assistant
spec:
  type: LoadBalancer
  selector:
    app: homeassistant-label
  ports:
  - name: homeassistant
    protocol: TCP
    port: 8123
    targetPort: 8123